name: pep8_check_and_test

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: pipenv
          python-version: '3.11'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run flake8
        run: pipenv run flake8 app/

      - name: Run tests
        run: pipenv run pytest
        