name: Python Lint

on:
  push:
    paths:
      - 'app/**'
      - 'Pipfile'
      - 'Pipfile.lock'
  pull_request:
    paths:
      - 'app/**'
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies with Pipenv
        run: |
          pip install pipenv
          pipenv install

      - name: Run flake8
        run: flake8 app/
