name: Python Lint

on:
  push:
    paths:
      - 'app/**'
      - 'Pipfile'
      - 'Pipfile.lock'
  pull_request:
    paths:
      - 'app/**'
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv
        
      - name: Install dependencies with Pipenv
        run: pipenv install --dev

      - name: Run flake8
        run: flake8 app/
